#!/usr/bin/env python3

import pathlib
import subprocess
import sys

MODEL_DIR = '/opt/ml/model'

if __name__ == '__main__':
    for path in pathlib.Path(MODEL_DIR).glob('**/[!.]*'):
        if path.is_dir():
            path.relative_to(MODEL_DIR).mkdir(exist_ok=True)
        elif not path.relative_to(MODEL_DIR).is_symlink():
            path.relative_to(MODEL_DIR).symlink_to(path)

    subprocess.run([sys.executable, 'server_fastapi.py'])
