#!/usr/bin/env python3

import subprocess
import sys

from initialize import download_bert_models

MODEL_DIR = "/opt/ml/model"

if __name__ == "__main__":
    download_bert_models()

    subprocess.run(
        [
            sys.executable,
            "server_fastapi.py",
            "--dir",
            MODEL_DIR,
        ],
    )
