#!/usr/bin/env python

import subprocess
import sys

from initialize import download_bert_models

MODEL_DIR = "/opt/ml/model"

if __name__ == "__main__":
    download_bert_models()

    subprocess.run(
        [
            sys.executable,
            "serve.py",
            "--model_dir",
            MODEL_DIR,
        ],
        check=True,
    )
