#!/usr/bin/env python

import subprocess
import sys
import traceback
from pathlib import Path

import yaml

INPUT_DIR = "/opt/ml/input"
OUTPUT_DIR = "/opt/ml/output"
MODEL_DIR = "/opt/ml/model"

if __name__ == "__main__":
    try:
        subprocess.run(
            [
                sys.executable,
                "initialize.py",
                "--skip_jvnv",
            ],
            check=True,
        )

        with Path("configs", "paths.yml").open() as f:
            paths = yaml.safe_load(f)

        with Path("configs", "paths.yml").open(mode="w") as f:
            yaml.dump(paths | {"assets_root": MODEL_DIR}, f)

        subprocess.run(
            [
                sys.executable,
                "train.py",
                "--input_dir",
                INPUT_DIR,
                "--model_dir",
                MODEL_DIR,
            ],
            check=True,
        )
    except Exception as e:
        with Path(OUTPUT_DIR, "failure").open(mode="w") as f:
            f.write(str(e) + "\n" + traceback.format_exc())
        raise
